### ISSUE TITLE
[Community Translation][WIP] Russian Translation

### ISSUE THREAD

**Issue by gbezyuk** [logaretm/vee-validate-docs#9]
Hi there. @translation-gang has started a [translation project for this documentation](https://github.com/translation-gang/ru.vee-validate-docs). It's a pity that docs are not separated from the code, though.

**Comment by logaretm** [comment]
@gbezyuk yea, sorry it was a bit of short sight, do you need any help or have an advice that I should do so you guys can have an easier time?

**Comment by gbezyuk** [comment]
@theOnlyBoy is doing the actual work, so please assist him. Thank you!

**Comment by theOnlyBoy** [comment]
@logaretm Hey man! Look, maybe you can start to split texts from a code, and I'll start to translate them as a plain text. When you'll be ready with new format — just us know, we'll format translated texts. Thx!

**Comment by theOnlyBoy** [comment]
@logaretm One more question: I'm unable to build the project. Tried many versions of node/npm, the latest as well. Any ideas?
`keywords if/then/else require v5 option
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! docs@1.0.0 dev: `webpack-dev-server --inline --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the docs@1.0.0 dev script 'webpack-dev-server --inline --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the docs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs docs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls docs
npm ERR! There is likely additional logging output above.

`

**Comment by logaretm** [comment]
@theOnlyBoy Hey, I will start splitting them after my exam today, should be done by the night, I will inform you once done.

Regarding the build, I tried to clone the repo again but I installed the dependencies using `yarn` and everything seems in order. Probably you have another process that is using port `8080` which is preventing the dev server from starting.

**Comment by gbezyuk** [comment]
@logaretm hope your exam went well ;)

**Comment by logaretm** [comment]
@gbezyuk Better than expected 😄 thank you.

So does something [like that](https://github.com/logaretm/vee-validate-docs/blob/split_strings/src/js/strings/home.js) works for you guys?

**Comment by gbezyuk** [comment]
@logaretm glad to hear that! yep, it seems quite okay to me. Markdown could be better, but anyway we could totally work with JSON too.

**Comment by theOnlyBoy** [comment]
@logaretm hey man, any updates?

**Comment by logaretm** [comment]
@theOnlyBoy Sorry, I was updating the docs for the new syntax. I will get back to extracting text once done as I don't want us to repeat any work. I might also rewrite the docs in pug considering it will make things a little bit cleaner.

**Comment by gbezyuk** [comment]
@logaretm please consider using simple markdown and separating the data from the layout this way

**Comment by logaretm** [comment]
@gbezyuk Sure, I will try different things.

**Comment by gbezyuk** [comment]
@logaretm you may be inspired by vuejs's docs approach at https://github.com/vuejs/vuejs.org
basically, they use github-pages with a custom generator, and results are awesome both in terms of UX and in terms of maintainability and translatability.

**Comment by gbezyuk** [comment]
@logaretm how are you doing man?

**Comment by logaretm** [comment]
@gbezyuk sorry mate, I got busy into work, I think I figured out what to do with the docs, I will follow a similar approach to `vuelidate` and `vue-multiselect` I will have the actual site written in jade, and the text content in markdown. since it is closer to what I have already.

What do you think?

**Comment by gbezyuk** [comment]
@logaretm that's suits our needs perfectly.

**Comment by logaretm** [comment]
@gbezyuk I think I've finished refactoring it, check it here: https://github.com/logaretm/vee-validate-docs/tree/feature/refactor

You have the main templates in `src/templates`.
The markdown are located in `src/templates/markdown`

Is that good enough? if you have additional notes I will be happy to help. I will merge it with master if you think it is suitable.

**Comment by gbezyuk** [comment]
@logaretm looks totally great to me. ping @theOnlyBoy

**Comment by theOnlyBoy** [comment]
Hey guys! Wake up the world of the better!

I'll take a look as soon as possible.

**Comment by gbezyuk** [comment]
@logaretm could you please move original docs in '/en' folder, so locations can thus be placed next to it?

**Comment by logaretm** [comment]
@gbezyuk so It would look like `src/templates/markdown/en`?

**Comment by gbezyuk** [comment]
Yep, something like that. Although I'm not sure if actual texts should be labeled as templates. Anyway, we just need a way to put the translation next to original docs.

**Comment by logaretm** [comment]
Okay, do you have a better structure in mind? I though you guys will fork it and edit the text in place.

**Comment by gbezyuk** [comment]
For now let's wrap the original within "en" folder.

**Comment by logaretm** [comment]
done.
